version: '3.9'

services:
  backend:
    build:
      context: ./backend
    container_name: moneyflow-backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    environment:
      - FLASK_ENV=development

  frontend:
    image: nginx:alpine
    container_name: moneyflow-frontend
    ports:
      - "8080:80"
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
